# Generated by Django 5.0.1 on 2024-02-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookinguser_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinguser',
            name='name',
        ),
    ]
