# Generated by Django 5.0.1 on 2024-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bookinguser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='date',
            field=models.CharField(default='', max_length=40),
        ),
    ]
