# Generated by Django 5.0.1 on 2024-02-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bookinguser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
