# Generated by Django 5.0.1 on 2024-02-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookinguser_gender_bookinguser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinguser',
            name='peoples',
        ),
    ]
